version: '2'
services:
  core-postgresql:
    image: postgres:12.1
    # volumes:
    #     - ~/volumes/jhipster/core/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=core
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
